plugins{ java }
 dependencies{ implementation("org.wildfly.core:wildfly-server:29.0.1.Final")}
dependencies{ implementation(project(":project1"))}
dependencies{ implementation(project(":project2"))}
dependencies{ implementation(project(":project3"))}
dependencies{ implementation(project(":project4"))}
dependencies{ implementation(project(":project5"))}
dependencies{ implementation(project(":project6"))}
dependencies{ implementation(project(":project7"))}
dependencies{ implementation(project(":project8"))}
dependencies{ implementation(project(":project9"))}
dependencies{ implementation(project(":project10"))}
dependencies{ implementation(project(":project11"))}
dependencies{ implementation(project(":project12"))}
dependencies{ implementation(project(":project13"))}
dependencies{ implementation(project(":project14"))}
dependencies{ implementation(project(":project15"))}
dependencies{ implementation(project(":project16"))}
dependencies{ implementation(project(":project17"))}
dependencies{ implementation(project(":project18"))}
dependencies{ implementation(project(":project19"))}
dependencies{ implementation(project(":project20"))}
dependencies{ implementation(project(":project21"))}
dependencies{ implementation(project(":project22"))}
dependencies{ implementation(project(":project23"))}
dependencies{ implementation(project(":project24"))}
dependencies{ implementation(project(":project25"))}
dependencies{ implementation(project(":project26"))}
dependencies{ implementation(project(":project27"))}
dependencies{ implementation(project(":project28"))}
dependencies{ implementation(project(":project29"))}
dependencies{ implementation(project(":project30"))}
dependencies{ implementation(project(":project31"))}
dependencies{ implementation(project(":project32"))}
dependencies{ implementation(project(":project33"))}
dependencies{ implementation(project(":project34"))}
dependencies{ implementation(project(":project35"))}
dependencies{ implementation(project(":project36"))}
dependencies{ implementation(project(":project37"))}
dependencies{ implementation(project(":project38"))}
dependencies{ implementation(project(":project39"))}
dependencies{ implementation(project(":project40"))}
dependencies{ implementation(project(":project41"))}
dependencies{ implementation(project(":project42"))}
dependencies{ implementation(project(":project43"))}
dependencies{ implementation(project(":project44"))}
dependencies{ implementation(project(":project45"))}
dependencies{ implementation(project(":project46"))}
dependencies{ implementation(project(":project47"))}
dependencies{ implementation(project(":project48"))}
dependencies{ implementation(project(":project49"))}
dependencies{ implementation(project(":project50"))}
dependencies{ implementation(project(":project51"))}
dependencies{ implementation(project(":project52"))}
dependencies{ implementation(project(":project53"))}
dependencies{ implementation(project(":project54"))}
dependencies{ implementation(project(":project55"))}
dependencies{ implementation(project(":project56"))}
dependencies{ implementation(project(":project57"))}
dependencies{ implementation(project(":project58"))}
dependencies{ implementation(project(":project59"))}
dependencies{ implementation(project(":project60"))}
dependencies{ implementation(project(":project61"))}
dependencies{ implementation(project(":project62"))}
dependencies{ implementation(project(":project63"))}
dependencies{ implementation(project(":project64"))}
dependencies{ implementation(project(":project65"))}
